import { SearchableSection } from "../Media";

const searchableSections: SearchableSection[] = [
  {
    text: "Test 123",
    startTime: 0,
    endTime: 400,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Hello",
    startTime: 0,
    endTime: 200,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Uno",
    startTime: 11,
    endTime: 50,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Dos",
    startTime: 51,
    endTime: 100,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Tres",
    startTime: 125,
    endTime: 180,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Another test",
    startTime: 201,
    endTime: 399,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Cuatro",
    startTime: 201,
    endTime: 220,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Cinco",
    startTime: 240,
    endTime: 300,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Seis",
    startTime: 304,
    endTime: 380,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Tit amet",
    startTime: 401,
    endTime: 860,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "In voluptate velit",
    startTime: 401,
    endTime: 502,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "One",
    startTime: 403,
    endTime: 420,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Another one",
    startTime: 420,
    endTime: 430,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "A third one",
    startTime: 440,
    endTime: 450,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Fourth",
    startTime: 450,
    endTime: 460,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "The fifth",
    startTime: 460,
    endTime: 470,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "And the sixth as well",
    startTime: 471,
    endTime: 488,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Esse cillum dolore eu",
    startTime: 503,
    endTime: 860,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Ut enim ad",
    startTime: 550,
    endTime: 603,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Minima veniam",
    startTime: 700,
    endTime: 789,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
];

export default searchableSections;
