import { SearchableSection } from "../Media";

const searchableSections: SearchableSection[] = [
  {
    text: "Section 1",
    startTime: 0,
    endTime: 400,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Lorem ipsum",
    startTime: 0,
    endTime: 200,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Curabitur at",
    startTime: 11,
    endTime: 50,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Lectus massa",
    startTime: 51,
    endTime: 100,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Sed accumsan",
    startTime: 125,
    endTime: 180,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Dolor sit amet",
    startTime: 201,
    endTime: 399,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Posuere massa",
    startTime: 201,
    endTime: 220,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Vel dictum",
    startTime: 240,
    endTime: 300,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Ut a mi id",
    startTime: 304,
    endTime: 380,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Section 2",
    startTime: 401,
    endTime: 860,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Consectetur",
    startTime: 401,
    endTime: 502,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Elit venenatis",
    startTime: 403,
    endTime: 420,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Accumsan eu",
    startTime: 420,
    endTime: 430,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Eu orci",
    startTime: 440,
    endTime: 450,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Aliquam vel",
    startTime: 450,
    endTime: 460,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Sem consectetur",
    startTime: 460,
    endTime: 470,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Porttitor lorem sed",
    startTime: 471,
    endTime: 488,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Adipiscing elit",
    startTime: 503,
    endTime: 860,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Tristique purus",
    startTime: 550,
    endTime: 603,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
  {
    text: "Ut euismod",
    startTime: 700,
    endTime: 789,
    videoTitle: "View from a blue moon",
    isCue: false,
  },
];

export default searchableSections;
