import { SearchableCue } from "../Media";

const cues: SearchableCue[] = [
  {
    startTime: 15,
    endTime: 18.13,
    text: "At the left we can see…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 18.13,
    endTime: 20.5,
    text: "At the right we can see the—",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 20.5,
    endTime: 21.98,
    text: "…the head-snarlers.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 21.98,
    endTime: 24.55,
    text: "Everything is safe… Perfectly safe.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 24.55,
    endTime: 25.77,
    text: "Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 26.12,
    endTime: 27.22,
    text: "Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 28.62,
    endTime: 30.104,
    text: "Watch out!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 46.56,
    endTime: 48.26,
    text: "Are you hurt?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 51.99,
    endTime: 54.2,
    text: "I don’t think so. You?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 55.52,
    endTime: 57.09,
    text: "I’m OK.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 57.09,
    endTime: 61.11,
    text: "Get up, Emo! It’s not safe here.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 62.03,
    endTime: 63.229,
    text: "Let’s go.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 63.22,
    endTime: 65.19,
    text: "What’s next?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 65.19,
    endTime: 66.96,
    text: "You’ll see!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 67.68,
    endTime: 68.84,
    text: "You’ll see!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 76.03,
    endTime: 78.48,
    text: "Emo! This way.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 94.23,
    endTime: 95.48,
    text: "Follow me!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 131.1,
    endTime: 132.521,
    text: "Hurry, Emo!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 168.438,
    endTime: 170.063,
    text: "You’re not paying attention!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 170.063,
    endTime: 174.313,
    text: "I–I just want to answer the phone.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 174.31,
    endTime: 177.04,
    text: "Emo, look… I mean, listen.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 179.14,
    endTime: 182,
    text: "You have to learn to listen.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 183.14,
    endTime: 185.04,
    text: "This is not some game.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 185.04,
    endTime: 189.18,
    text: "You… I mean, <i>we</i>. We could easily die out here.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 190.01,
    endTime: 194.396,
    text: "Listen… Listen to the sounds of the machine.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 198.05,
    endTime: 200,
    text: "Listen to your breathing.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 266.646,
    endTime: 269.313,
    text: "Well, don’t you ever get tired of this?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 269.313,
    endTime: 271.09,
    text: "Tired!?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 271.09,
    endTime: 273.313,
    text: "Emo, the machine is like…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 273.31,
    endTime: 275.26,
    text: "Like clockwork!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 275.26,
    endTime: 277.063,
    text: "One move out of place…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 277.063,
    endTime: 279.12,
    text: "…and you’re ground to a pulp.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 280.95,
    endTime: 282.104,
    text: "But isn’t it—",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 282.104,
    endTime: 286.03,
    text: "Pulp, Emo! Is that what you want? <i>Pulp</i>?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 287.104,
    endTime: 290.42,
    text: "Emo, your goal in life…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 290.44,
    endTime: 291.95,
    text: "…pulp!?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 341.31,
    endTime: 343.42,
    text: "Emo, close your eyes.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 344.15,
    endTime: 345.396,
    text: "–Why?\n–Now!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 351.15,
    endTime: 351.97,
    text: "OK.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 353.11,
    endTime: 354.68,
    text: "Good.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 359.42,
    endTime: 362.1,
    text: "What do you see at your left side, Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 364.02,
    endTime: 366,
    text: "–Nothing.\n–Really?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 366,
    endTime: 367.58,
    text: "No, nothing at all.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 367.58,
    endTime: 371.98,
    text:
      "Really? A–And at your right? What do you see at your right side, Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 373.31,
    endTime: 376.84,
    text: "The same, Proog. Exactly the same…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 376.84,
    endTime: 379.896,
    text: "–…nothing!\n–Great.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 399.97,
    endTime: 402.72,
    text: "Listen, Proog! Do you hear that?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 403.44,
    endTime: 404.56,
    text: "Can we go here?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 405.063,
    endTime: 406.56,
    text: "–There?\n–Yeah!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 406.58,
    endTime: 408.188,
    text: "It isn’t safe, Emo.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 409.14,
    endTime: 412.01,
    text: "–B–But…\n–Trust me, it’s not.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 413.02,
    endTime: 414.17,
    text: "Well, maybe I could…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 414.17,
    endTime: 415.146,
    text: "No.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 417.1,
    endTime: 418.82,
    text: "–But…\n–No!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 418.82,
    endTime: 420.24,
    text: "No!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 420.771,
    endTime: 423.05,
    text: "Any further questions, Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 423.97,
    endTime: 425.09,
    text: "N–No.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 429.05,
    endTime: 430.08,
    text: "Emo?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 431.14,
    endTime: 433.08,
    text: "Emo, why!?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 433.08,
    endTime: 435.36,
    text: "Emo, why…?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 435.36,
    endTime: 438.84,
    text: "Why can’t you see the beauty of this place?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 438.84,
    endTime: 440.646,
    text: "The way it works.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 440.646,
    endTime: 443.92,
    text: "How… How <i>perfect</i> it is.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 443.92,
    endTime: 447.04,
    text: "No, Proog, I don’t see.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 447.04,
    endTime: 449.97,
    text: "I don’t see because there’s nothing there.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 451.05,
    endTime: 455.24,
    text: "And why should I trust my life to something that isn’t there?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 455.24,
    endTime: 456.6,
    text: "Well, can you tell me that?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 456.6,
    endTime: 457.38,
    text: "Emo…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 457.38,
    endTime: 458.92,
    text: "Answer me!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 462.97,
    endTime: 464,
    text: "Proog…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 465.05,
    endTime: 466.854,
    text: "…you’re a sick man!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 466.854,
    endTime: 468.91,
    text: "Stay away from me!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 472.188,
    endTime: 474.854,
    text: "No! Emo! It’s a trap!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 475.42,
    endTime: 476.979,
    text: "Hah, “it’s a trap!”",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 476.979,
    endTime: 481.229,
    text: "At the left side you can see the Hanging Gardens of Babylon!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 481.96,
    endTime: 483.95,
    text: "How’s that for a trap?",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 485.72,
    endTime: 486.92,
    text: "No, Emo.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 489,
    endTime: 492.64,
    text: "At the right side you can see—well guess what…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 492.64,
    endTime: 494.66,
    text: "…the Colossus of Rhodes!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 495.32,
    endTime: 496.39,
    text: "No!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 496.396,
    endTime: 500.16,
    text: "The Colossus of Rhodes! And it is here just for you, Proog.",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 500.16,
    endTime: 501.688,
    text: "Just for you!",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 531,
    endTime: 533.021,
    text: "It is there…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 533.021,
    endTime: 536.04,
    text: "I’m telling you, Emo…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
  {
    startTime: 537,
    endTime: 539.86,
    text: "…it is… there…",
    videoTitle: "Elephants dream",
    isCue: true,
  },
];

export default cues;
