import { SearchableSection } from "../Media";

const searchableSections: SearchableSection[] = [
  {
    text: "Section 1",
    startTime: 0,
    endTime: 400,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Proin dui neque",
    startTime: 0,
    endTime: 200,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Placerat iaculis",
    startTime: 11,
    endTime: 50,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Nullam a nibh",
    startTime: 51,
    endTime: 100,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Varius elit",
    startTime: 125,
    endTime: 180,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Efficitur sit amet",
    startTime: 201,
    endTime: 399,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Venenatis leo",
    startTime: 201,
    endTime: 220,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Curabitur porta",
    startTime: 240,
    endTime: 300,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Quam a diam",
    startTime: 304,
    endTime: 380,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Section 2",
    startTime: 401,
    endTime: 860,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Amet tellus vel",
    startTime: 401,
    endTime: 502,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Lacinia vestibulum",
    startTime: 403,
    endTime: 420,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Suspendisse sollicitudin",
    startTime: 420,
    endTime: 430,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Eget arcu",
    startTime: 440,
    endTime: 450,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Vel convalliss",
    startTime: 450,
    endTime: 460,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Integer feugiat",
    startTime: 460,
    endTime: 470,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Sodales enim",
    startTime: 471,
    endTime: 488,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Feugiat faucibus",
    startTime: 503,
    endTime: 860,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Sed fermentum",
    startTime: 550,
    endTime: 603,
    videoTitle: "Elephants dream",
    isCue: false,
  },
  {
    text: "Etiam in feugiat",
    startTime: 700,
    endTime: 789,
    videoTitle: "Elephants dream",
    isCue: false,
  },
];

export default searchableSections;
